import Head from "next/head";
import styled from "styled-components";
import { BsArrowRightShort } from "react-icons/bs";
import Link from "next/link";
import bg from "./../public/homePageBackground.jpg";

const Main = styled.main`
  display: flex;
  justify-content: center;
  align-items: center;
  flex-direction: column;
  gap: 1rem;
  min-height: 100vh;
  background: linear-gradient(0deg, rgba(0, 0, 0, 0.75), rgba(0, 0, 0, 0.75)),
    url(${bg.src}) no-repeat center center/cover;
  color: var(--light-color);
  text-align: center;
  h1 {
    font-size: 2.5rem;
    font-weight: 600;
    margin-block: 0.5rem;
  }
  p {
    font-size: 1.25rem;
    font-weight: 400;
    margin-block: 0.5rem;
  }
  & a {
    transition: all 0.15s;
    padding: 1rem 1.5rem;
    border: 1px solid rgb(var(--light-color));
    border-radius: 0.25rem;
    background-color: var(--light-color);
    color: var(--light-color);
    font-size: 1rem;
    font-weight: 600;
    cursor: pointer;
    & svg {
      transition: all 0.15s;
      scale: 0;
      visibility: hidden;
      opacity: 0;
      width: 0;
    }
    &:hover {
      display: flex;
      align-items: center;
      justify-content: center;
      gap: 0.5rem;
      border-color: rgb(var(--primary-color));
      & svg {
        scale: 1;
        visibility: visible;
        opacity: 1;
        width: auto;
      }
    }
  }
`;

export default function Home() {
  
  return (
    <>
      <Head>
        <title>Infotech Success Point</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main>
        <h1>Why join Infotech Success Point ?</h1>
        <p>Get career-ready with job-oriented learning</p>
        <Link href="/courses">
          Our Courses <BsArrowRightShort />
        </Link>
      </Main>
    </>
  );
}
